steps:
  - label: setup apps
    command:
      - "echo \"PWD: $PWD\""
      - .buildkite/setup_apps.sh

  - label: npm install
    command: npm install

  - wait

  - label: cypress tests
    command:
      - npm start
      - $(npm bin)/cypress run
