steps:
  - label: setup apps
    command:
      - .buildkite/setup_apps.sh

  - label: npm install
    command: npm install

  - wait

  - label: cypress tests
    command:
      - .buildkite/run_cypress_tests.sh
