#!/bin/bash

set -eu

if [ "$BUILDKITE_COMMAND" != "buildkite-agent pipeline upload" ] ; then
  brew install nvm
  source /usr/local/opt/nvm/nvm.sh
  nvm install 8.4.0
  nvm use 8.4.0
fi

export CURRENT_TAG=$(git describe --tags --abbrev=0)
echo "Current tag is: $CURRENT_TAG"
