#!/bin/bash

set -eu

if [ "$BUILDKITE_COMMAND" != "buildkite-agent pipeline upload" ] ; then
  export NVM_DIR="$HOME/.nvm"
  if [ -s "$NVM_DIR/nvm.sh" ]; then
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.4/install.sh | bash
  fi
  source "$NVM_DIR/nvm.sh" # This loads nvm
  nvm install 8.4
  nvm use 8.4
fi

echo "done"
